version: '3.1'
services:
  db:
    image: postgres:12.10
    restart: always
    container_name: test_2
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: mydb
    volumes:
       - ./data:/var/lib/postgresql/data
       - ./backup:/backup
    ports:
      - "5432:5432"
