version: '3.1'
services:
  db:
    image: postgres:13.1
    restart: always
    container_name: test_3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
    volumes:
#       - ./data:/var/lib/postgresql/data
       - ./backup:/backup
    ports:
      - "5432:5432"
